apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool-app
spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8081
        env:
        - name: HTTP_PORT
          value: "8081"
